import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";
import countries from "@/src/lib/leagues";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Football Leagues Site",
  description: "Generated by ama-manu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <Link href="/">FLS</Link>
          <div>
            <Menu>
              <MenuButton>Menu</MenuButton>
              <MenuItems>
                {countries.map((country) => (
                  country.leagues.map((league) => 
                    <MenuItem key={league.name}>
                      {/* <div>{league.name}</div> */}
                      <Link href={`/${country.internalURL}/${league.shortcut}`}>{league.name}</Link>
                    </MenuItem>
                  )
                ))}
              </MenuItems>
            </Menu>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
